name: Test Action

on: 
  push:
    branches:
    - 'dev-rochelle'
  pull_request:
    branches:
    - 'dev_rochelle'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Print test
      run: echo "Hello World"
